### ISSUE TITLE
404 Not Found: @bentley/imodeljs-darwin-x64@0.124.0

### ISSUE THREAD

**Issue by alexander7161** [imodeljs/imodeljs-samples#3]
npm install errors on MacOS 10.14.5 with node 10.15.1.

```> @bentley/imodeljs-native@0.124.0 postinstall /Documents/Hackathons/Infrahack/simple-viewer-app/node_modules/@bentley/imodeljs-native
> node ./installNativePlatform.js

(node:11417) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
npm install --no-save @bentley/imodeljs-darwin-x64@0.124.0
/Documents/Hackathons/Infrahack/simple-viewer-app/node_modules/@bentley/imodeljs-native/installNativePlatform.js:40
      throw error;
      ^

Error: Command failed: npm install --no-save @bentley/imodeljs-darwin-x64@0.124.0
npm ERR! code E404
npm ERR! 404 Not Found: @bentley/imodeljs-darwin-x64@0.124.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2019-05-17T08_55_48_793Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)

**Comment by calebmshafer** [comment]
@alexander7161  MacOS is now officially supported as of iModel.js 1.12.0. Let us know if you face any issues when using it. Thanks!
